name: Copybara Watcher

on:
  status:
  push:
    branches: [ "main" ]

jobs:
  debug:
    name: debug
    runs-on: ubuntu-latest
    steps:
    - name: Dump Github Context
      run: echo '${{ toJSON(github) }}'

  fake_status:
    name: Add a fake status for testing
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    steps:
    - name: Create status
      run: |
        curl --request POST \
        --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha || github.event.sha }} \
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header 'content-type: application/json' \
        --data '{
          "state": "success",
          "context": "import/copybara",
          "target_url": "${{ github.event.workflow_run.html_url }}"
          }' \
        --fail

  copybara_status:
    name: comment
    if: github.event.state == 'success' && github.event.context == 'import/copybara'
    runs-on: ubuntu-latest
    steps:
    - name: Dump Github Event
      run: echo '${{ toJSON(github.event) }}'
