name: Copybara Watcher

on:
  status:
  # push:
  #   branches: [ "main" ]

jobs:
  debug:
    name: debug
    runs-on: ubuntu-latest
    steps:
    - name: Dump Github Context
      run: echo '${{ toJSON(github) }}'

  fake_status:
    name: Add a fake status for testing
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    steps:
    - name: Sleep for 120 seconds
      run: sleep 30s
      shell: bash
    - name: Create fake status
      run: |
        curl --request POST \
        --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha || github.event.sha }} \
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header 'content-type: application/json' \
        --data '{
          "state": "success",
          "context": "import/copybara",
          "target_url": "${{ github.event.workflow_run.html_url }}"
          }' \
        --fail

  copybara_import_status:
    name: Check Import
    runs-on: ubuntu-latest
    steps:
    - name: Wait commit status
      uses: cloudposse/github-action-wait-commit-status@main
      with:
        repository: ${{ github.repository }}
        sha: ${{ github.sha }}
        status: import/copybara
        check-retry-count: 2
        check-retry-interval: 10
    - name: after commit status wait
      run: echo 'hello world!'