name: PR Watcher
on:
  push:
    branches: ["main"]
  workflow_dispatch:
  # schedule:
  #   - cron: "*/5 * * * *" # Every 5 minutes

jobs:
  check_copybara_import:
    name: Check Copybara Import status
    runs-on: ubuntu-latest
    steps:
      - name: List Pull Requests
        uses: actions/github-script@v6
        with:
          script: |
            const pulls = github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open'
              base: 'main',
            });

            for (const pull of pulls) {
              const number = pull.number;
              const sha = pull.head.sha;
              console.log(number, sha);
            }
