name: PR Watcher
on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *" # Every 10 minutes

jobs:
  check:
    name: Check Copybara Import Status
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: List Pull Requests
        uses: actions/github-script@v6
        with:
          script: |
            const pulls = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              base: 'main',
            });

            for (const pull of pulls.data) {
              const query = `query($owner:String!, $name:String!, $pullNumber:Int!, $statusContext:String!) {
                repository(owner:$owner, name:$name) {
                  pullRequest(number:$pullNumber) {
                    commits(last:1) {
                      nodes {
                        commit {
                          status {
                            context(name: $statusContext) {
                              state
                              targetUrl
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }`;
              const result = await github.graphql(query, {
                owner: context.repo.owner,
                name: context.repo.repo,
                pullNumber: pull.number,
                statusContext: 'import/copybara',
              });
              const nodes = result.repository.pullRequest.commits.nodes;
              const commit = nodes[0].commit;
              if (commit && commit.status && commit.status.context) {
                await github.rest.actions.createWorkflowDispatch({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  ref: 'main',
                  workflow_id: 'pr-manager.yml',
                  inputs: {
                    pullNumber: pull.number.toString(),
                    state: commit.status.context.state,
                    targetUrl: commit.status.context.targetUrl,
                  },
                });
              }
            }
