name: PR Watcher
on:
  push:
    branches: ["main"]
  workflow_dispatch:
  # schedule:
  #   - cron: "*/5 * * * *" # Every 5 minutes

jobs:
  check_copybara_import:
    name: Check Copybara Import status
    runs-on: ubuntu-latest
    steps:
      - name: List Pull Requests
        id: list_prs
        run: |
          echo "list_prs_response<<EOF" >> $GITHUB_OUTPUT
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos${{ github.owner }}/${{ github.repository }}/pulls?state=open&base=main
          echo EOF >> $GITHUB_OUTPUT
      - run: |
          echo '${{ steps.list_prs.outputs.list_prs_response }}'
          echo '${{ fromJson(steps.list_prs.outputs.list_prs_response) }}'
