name: PR Watcher
on:
  push:
    branches: ["main"]
  workflow_dispatch:
  # schedule:
  #   - cron: "*/5 * * * *" # Every 5 minutes

jobs:
  check_copybara_import:
    name: Check Copybara Import status
    runs-on: ubuntu-latest
    steps:
      - name: List Pull Requests
        uses: actions/github-script@v6
        with:
          script: |
            let pulls;
            try {
              pulls = await github.rest.pulls.list({
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: 'open',
                base: 'main',
              });
            } catch (err) {
              throw err;
              return;
            }

            for (const pull of pulls.data) {
              const number = pull.number;
              const sha = pull.head.sha;
              console.log(number, sha);

              const query = `query($owner:String!, $name:String!, $pr_number:Int!) {
                repository(owner:$owner, name:$name) {
                  pullRequest(number:$pr_number) {
                    commits(last:1) {
                      nodes {
                        commit {
                          status {
                            copybara_import_status: context('import/copybara')
                            other_status: context('asdff')
                          }
                        }
                      }
                    }
                  }
                }
              }`;
              const result = await github.graphql(query, {
                owner: context.repo.owner,
                name: context.repo.repo,
                pr_number: pull.number,
              });
              console.log(result)
            }
