name: PR Watcher
on:
  push:
    branches: ["main"]
  workflow_dispatch:
  # schedule:
  #   - cron: "*/5 * * * *" # Every 5 minutes

jobs:
  check_copybara_import:
    name: Check Copybara Import status
    runs-on: ubuntu-latest
    steps:
      - name: List Pull Requests
        uses: actions/github-script@v6
        with:
          script: |
            const pulls = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              base: 'main',
            });

            for (const pull of pulls.data) {
              const query = `query($owner:String!, $name:String!, $pullNumber:Int!, $statusContext:String!) {
                repository(owner:$owner, name:$name) {
                  pullRequest(number:$pullNumber) {
                    commits(last:1) {
                      nodes {
                        commit {
                          status {
                            context(name: $statusContext) {
                              state
                              targetUrl
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }`;
              const result = await github.graphql(query, {
                owner: context.repo.owner,
                name: context.repo.repo,
                pullNumber: pull.number,
                statusContext: 'import/copybara',
              });
              const status = result.repository.pullRequest.commits.nodes.commit.status;
              if (status) {
                if (status.state == 'success') {
                  console.log(pull.number, status.targetUrl)
                }
              }
            }
